language: go

services:
  - docker

sudo: required

go:
  - 1.11.x

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
  - npm install -g yarn

stages:
  - name: test
  - name: staging
    if: branch = master AND type = push
  - name: release
    if: tag IS present
  - name: release-helm
    if: tag IS present

jobs:
  include:
    - name: 'Tests'
      stage: test
      script:
        - make validate-commit
        - make lint
        - make test-frontend
        - make test-coverage
    - name: 'Integration Tests'
      stage: test
      script:
        - make packages
        - ./build/bin/bblfsh-web &
        - sleep 5 # give bblfsh-web some time to start
        - curl 127.0.0.1:9999 | grep 'Babelfish Web'
    - name: 'Release'
      stage: release
      script:
        - make packages
        - DOCKER_PUSH_LATEST=true make docker-push
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true
        on:
          tags: true
          go: 1.11.x
    - name: 'Deploy to staging'
      stage: staging
      script:
        - make packages
        - DOCKER_PUSH_MASTER=true make docker-push
        #HELM_RELEASE name is also harcoded in the .helm_staging file in order to use the AntiAffinity Rules.
        - HELM_RELEASE=bblfsh-web HELM_CHART=bblfsh-web K8S_NAMESPACE=default HELM_ARGS="--repo https://src-d.github.io/charts/ --version 0.8.0 --set image.tag=dev-$(git rev-parse --short HEAD) -f .helm_staging.yml" make deploy
    - name: 'Deploy to production'
      stage: release-helm
      script:
        #HELM_RELEASE name is also harcoded in the .helm_production file in order to use the AntiAffinity Rules.
        - B64_CA_CRT=$B64_CA_CRT_PROD SERVICE_ACCOUNT_TOKEN=$SERVICE_ACCOUNT_TOKEN_PROD CLUSTER_ENDPOINT=$CLUSTER_ENDPOINT_PROD HELM_RELEASE=bblfsh-web HELM_CHART=bblfsh-web K8S_NAMESPACE=default HELM_ARGS="--repo https://src-d.github.io/charts/ --version 0.8.0 --set image.tag=$TRAVIS_TAG -f .helm_production.yml" make deploy
